---
- name: "Desktop"
  hosts: "*"
  vars:
    username: charlieegan3
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: run ansible galaxy
    local_action: command ansible-galaxy install -r requirements.yaml 

  - name: "pschyska/alacritty"
    include_role:
      name: edmondscommerce.copr-repository
    vars:
      copr_repository: pschyska/alacritty

  - name: install packages
    dnf:
      name:
      - sway-1.4
      - chromium
      state: latest
    become: yes
