- name: install packages
  dnf:
    name:
    - docker-ce-19.03.13
    - docker-ce-cli-19.03.13
    - docker-compose-1.25.4
    - containerd.io-1.3.7
    state: latest
  become: yes

- name: set cgroups exception
  shell: |
    grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  become: true

- name: enable and start docker
  shell: |
    systemctl enable docker
    systemctl start docker
  become: true

- name: docker post install
  shell: |
    groupadd docker
    usermod -aG docker {{ username }}
  become: true
