- name: create user account
  user:
    name: "{{ username }}"
- name: install home dir
  copy:
    src: HOME/
    dest: /home/{{ username }}/
    owner: "{{ username }}"
- name: set local bin permissions
  shell: |
    chmod +x /home/{{ username }}/.local/bin/*
  args:
    warn: false
  become: true
