- name: get kernel version
  shell: uname -r | cut -d- -f1
  args:
    warn: false
  register: kernel_version

- name: install packages
  dnf:
    name:
    - alacritty-0.5.0 # terminal emulator
    - vim-enhanced-8.2.1551
    - automake-1.16.1
    - chromium
    - gcc-10.0.1
    - htop-2.2.0
    - lshw-B.02.19.2
    - make-1:4.2.1
    - mako-1.4.1 # notification
    - sway-1.4
    - ulauncher-5.8.0
    # TODO work out why this doens't work for cloud vm
    # - kernel-headers-{{ kernel_version.stdout }} # needed for v4l2loopback
    # - kernel-devel-{{ kernel_version.stdout }} # needed for v4l2loopback
    - kernel-headers # needed for v4l2loopback
    - kernel-devel # needed for v4l2loopback
    - v4l2loopback-0.12.5 # screen recorder plugin
    - v4l2loopback-dkms-0.12.5 # screen recorder kernel module
    - vlc-1:3.0.11.1
    - ffmpeg-4.2.4
    - waybar-0.9.3
    - wl-clipboard-2.0.0
    - tmux-3.0a
    - direnv-2.21.2
    - fzf-0.22.0
    - ruby-2.7.1
    - golang-1.14.9
    - jq-1.6
    - mosh-1.3.2
    - ripgrep-12.1.1
    - rclone-1.51.0
    - hugo-0.69.0
    state: latest
  become: yes

- name: install gammastep
  command: dnf --disablerepo=* --enablerepo=rawhide --releasever=34 install -y gammastep-2.0.2
  args:
    warn: no
  become: yes

- name: remove packages
  dnf:
    name:
    # - vim-minimal
    state: absent
  become: yes
