- name: remove packages
  dnf:
    name:
    - NetworkManager-openconnect-gnome
    - NetworkManager-openvpn-gnome
    - NetworkManager-pptp-gnome
    - NetworkManager-ssh-gnome
    - NetworkManager-vpnc-gnome
    - cheese
    - desktop-backgrounds-gnome
    - evince
    - f32-backgrounds-gnome
    - fros-gnome
    - libgnomekbd
    - libreoffice-core
    - pinentry-gnome3
    - qgnomeplatform
    - rhythmbox
    - simple-scan
    state: absent
  become: yes

- name: remove gnome and libreoffice groups
  shell: |
    if [[ "$(dnf grouplist --installed | grep GNOME)" ]]; then
      dnf groupremove GNOME
    fi
    if [[ "$(dnf grouplist --installed | grep LibreOffice)" ]]; then
      dnf groupremove LibreOffice
    fi
  become: true
