- name: install vim-plug
  shell: |
    sh -c 'curl -fLo /home/{{ username }}/.local/share}/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  args:
    creates: /home/{{ username }}/.local/share}/nvim/site/autoload/plug.vim

- name: install plugins
  become: yes
  become_user: "{{ username }}"
  shell: |
    nvim -Es \
      -u "/home/charlieegan3/.local/share/nvim/site/autoload/plug.vim" \
      -u "/home/charlieegan3/.config/nvim/init.vim" \
      -c "PlugInstall" \
      -c qall \
      -V9vim.log
    if [ $? -ne 0 ]; then
      cat vim.log
    fi
    rm -rf vim.log

- name: update remote plugins
  become: yes
  become_user: "{{ username }}"
  shell: |
    nvim -Es \
      -u "/home/charlieegan3/.local/share/nvim/site/autoload/plug.vim" \
      -u "/home/charlieegan3/.config/nvim/init.vim" \
      -c "UpdateRemotePlugins" \
      -c qall \
      -V9vim.log
    if [ $? -ne 0 ]; then
      cat vim.log
    fi
    rm -rf vim.log

- name: install vimgo tools
  become: yes
  become_user: "{{ username }}"
  shell: |
    # this _should_ work but seems to hang when installing many tools
    nvim -Es \
      -u "/home/charlieegan3/.local/share/nvim/site/autoload/plug.vim" \
      -u "/home/charlieegan3/.config/nvim/plugged/vim-go/plugin/go.vim" \
      -u "/home/charlieegan3/.config/nvim/init.vim" \
      -c "GoInstallBinaries" \
      -c qall \
      -V9vim.log \
      main.go
    if [ $? -ne 0 ]; then
      exit 1
    fi
    rm -rf vim.log
    # go get golang.org/x/tools/cmd/guru
    # go get golang.org/x/tools/gopls
    # go get github.com/davidrjenni/reftools/cmd/fillstruct
    # go get github.com/rogpeppe/godef
    # go get github.com/fatih/motion
    # go get github.com/kisielk/errcheck
    # go get github.com/go-delve/delve/cmd/dlv
    # go get golang.org/x/tools/cmd/gorename
    # go get github.com/koron/iferr
    # go get golang.org/x/lint/golint
    # go get github.com/jstemmer/gotags
    # go get github.com/josharian/impl
    # go get golang.org/x/tools/cmd/goimports
    # go get github.com/golangci/golangci-lint/cmd/golangci-lint
    # go get github.com/fatih/gomodifytags
    # go get honnef.co/go/tools/cmd/keyify
    # go get honnef.co/go/tools/cmd/staticcheck
    # go get github.com/klauspost/asmfmt/cmd/asmfmt
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
    GO111MODULE: "{{ GO111MODULE }}"

- name: test can run go fmt
  become: yes
  become_user: "{{ username }}"
  shell: |
    bash -l -c "nvim -E -s -u \"$HOME/.config/nvim/init.vim\" -c \"exe ':GoFmt' | qall\" main.go"
    rm -f main.go

- name: install alacritty base16
  shell: |
    USERNAME={{ username }}
    git clone https://github.com/aaron-williamson/base16-alacritty /home/$USERNAME/.local/share/base16-alacritty
  args:
    creates: /home/{{ username }}/.local/share/base16-alacritty

- name: install alacritty from base config if missing
  shell: |
    USERNAME={{ username }}
    cp /home/$USERNAME/.config/alacritty/alacritty.base.yml \
      /home/$USERNAME/.config/alacritty/alacritty.yml
  args:
    creates: /home/{{ username }}/.config/alacritty/alacritty.yml
  become_user: "{{ username }}"
