- name: nvim
  dnf:
    name:
    - neovim-0.4.4
    - python3-neovim-0.4.1
    state: latest
  become: yes

- name: install vim-plug
  shell: |
    sh -c 'curl -fLo /home/{{ username }}/.local/share}/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  args:
    creates: /home/{{ username }}/.local/share}/nvim/site/autoload/plug.vim

- name: install plugins
  shell: |
    nvim +PlugInstall +qall
    nvim +UpdateRemotePlugins +qall
    nvim main.go +GoInstallBinaries +qall
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
    GO111MODULE: "{{ GO111MODULE }}"
  become_user: "{{ username }}"

- name: install alacritty base16
  shell: |
    USERNAME={{ username }}
    git clone https://github.com/aaron-williamson/base16-alacritty /home/$USERNAME/.local/share/base16-alacritty
  args:
    creates: /home/{{ username }}/.local/share/base16-alacritty

- name: install alacritty from base config if missing
  shell: |
    USERNAME={{ username }}
    cp /home/$USERNAME/.config/alacritty/alacritty.base.yml \
      /home/$USERNAME/.config/alacritty/alacritty.yml
  args:
    creates: /home/{{ username }}/.config/alacritty/alacritty.yml
  become_user: "{{ username }}"
