name: CI

on:
  push:
    branches: 
    - master 
  schedule:
  - cron:  "5 6 */7 * *"

jobs:
  suites:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Packer playbook
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      run: |
        make packer
